### PR TITLE
Airplane mode

### PR DESCRIPTION
**Pull request by QuentinFarizon**
## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation  changes
- [ ] Other... Please describe:

## PR Checklist
For bug fixes / features, please check if your PR fulfills the following requirements:

- [X] Testing has been carried out for the changes have been added
- [X] Regression testing has been carried out for existing functionality
- [X] Docs have been added / updated

## Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

## What testing has been done on the changes in the PR?

I am using this in production in my app.

## What testing has been done on existing functionality?
I have tested on several Android devices, spanning mulitple manufacturers and Android versions

### CODE REVIEW

**Comment by jacobg** [comment]
Very nice work!

@dpa99c Are there plans to merge this PR? Thanks.

**Comment by jacobg** [comment]
@QuentinFarizon Did you attempt an iOS implementation? Here's a reference implementation:
https://stackoverflow.com/questions/4804398/detect-airplane-mode-on-ios

**Comment by QuentinFarizon** [comment]
I've not tried yet, if there is interest for it, and if this get merged, I
can do it in another PR.

**Comment by QuentinFarizon** [comment]
@dpa99c I'm not sure about the failing build, it's pointing to errors that are present in the whole code, fixing it here would lose consistency or require to change everywhere

**Comment by QuentinFarizon** [comment]
@dpa99c is there any chance this could get merged ? If so could you help me understand the failing build?

**Pull request merged**
