### PR TITLE
Bumping minimist package version to resolve security audit

### PR DESCRIPTION
**Pull request by mread1208**
## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation  changes
- [X] Other... Please describe:

## PR Checklist
For bug fixes / features, please check if your PR fulfills the following requirements:

- [X] Testing has been carried out for the changes have been added
- [X] Regression testing has been carried out for existing functionality
- [X] Docs have been added / updated

## What is the purpose of this PR?
Updating the `minimist` npm package to the latest version to remove security audit, addresses #394  

## Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

## What testing has been done on the changes in the PR?
Testing in emulators to ensure services still prompt as expected.

## Other information

### CODE REVIEW

**Comment by ucsbricks** [comment]
Any news on this PR?

**Comment by ucsbricks** [comment]
@dpa99c  any news on this? Please merge to fix minimist < 1.2.3 vulnerability.

**Comment by dvag-lukas-rybacki** [comment]
@dpa99c updates on this one? Also showing security issues which are preventing to deploy on production

**Review by aabril4 — APPROVED** [review]

**Comment by aabril4** [comment]
Any news on this PR? I need merge with "minimist": "1.2.6" :(

**Pull request merged**
